//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
 using System.ComponentModel.DataAnnotations;
namespace test.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblUserInfo
    {
        
        public int iduser { get; set; }
        [Required(ErrorMessage ="Please full in this field")]
        [Display(Name ="UserName")]
        public string usernameus { get; set; }
        [DataType(DataType.Password)]
        [Required(ErrorMessage = "Please full in this field")]
        [Display(Name = "Password")]
        public string passwordus { get; set; }
    }
}
